name: Lint
# Super-Linter https://github.com/github/super-linter

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  VENV_DIR: /home/runner/work/_temp/_github_workflow

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "📂 Working folder is ${{inputs.working-directory}}"

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies with pip + requirements.txt
        shell: bash
        run: pip install -r requirements.txt

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.6.0
        env:
          DEFAULT_WORKSPACE: ${{inputs.working-directory}}/.github/linters
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_FLAKE8: true
          PYTHON_FLAKE8_CONFIG_FILE:  flake8
          VALIDATE_PYTHON_PYLINT: true
          PYTHON_PYLINT_CONFIG_FILE: pylint.toml
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: markdown-link-check.json
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: yaml-lint.yml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.token }}

# ~@:-]
